---
title: 'Scientific Writing Resources'
date: "October 2025"
output: html_document
---

# **Is writing what I need to do?**

Often, we skip straight to the idea of writing a report or paper, but sometimes that is not the most effective mechanism for the impact we want to have. The following resources are a good place to start on figuring out what type of impact is desired and how that aligns with a narrative we are building.  

- Hallemeier, J., Harris, A., Jumani, S. and Shaw, C., 2024. Pursuing Diverse Forms of Impact in Scientific Research. Bulletin of the Ecological Society of America, 105(1), pp.1-11. [pdf](https://www.jstor.org/stable/48754888?seq=1)  
- Kuehne, L.M., Twardochleb, L.A., Fritschie, K.J., Mims, M.C., Lawrence, D.J., Gibson, P.P., Stewart-Koster, B.E.N. and Olden, J.D., 2014. Practical science communication strategies for graduate students. Conservation Biology, 28(5), pp.1225-1235. [pdf](https://conbio.onlinelibrary.wiley.com/doi/epdf/10.1111/cobi.12305)  
- Leslie, H.M., Goldman, E., Mcleod, K.L., Sievanen, L., Balasubramanian, H., Cudney-Bueno, R., Feuerstein, A., Knowlton, N., Lee, K., Pollnac, R. and Samhouri, J.F., 2013. How good science and stories can go hand-in-hand. Conservation Biology, 27(5), pp.1126-1129. [pdf](https://ir.library.oregonstate.edu/downloads/9306t0420)


# **Writing is hard**

Scientific writing is challenging for everyone. No one sits down and writes a perfect paper in the first draft. We all have to work at it and share our tips and tricks. These resources are an *amazing* place to start for anyone writing a paper (for the first or fiftieth time). I've also included a few books on writing in general, which are a great reminder about how to craft stories, some of which are about science.   

- Dillard, A., 1989. The writing life. Landmark essays on writing process. [link](https://madstreetbooks.com/item/2QHtVTCGJR_9dwhCaNQx-A)  
- Drake JM, Han BA (2025) How to write a scientific paper in fifteen steps. PLoS Comput Biol 21(9): e1013505. [pdf](https://doi.org/10.1371/journal.pcbi.1013505)  
- Gopen, G.D. and Swan, J.A., 1990. The science of scientific writing. American scientist, 78(6), pp.550-558. [pdf](https://www.usenix.org/sites/default/files/gopen_and_swan_science_of_scientific_writing.pdf)  
- Hotaling, S., 2020. Simple rules for concise scientific writing. Limnol Oceanogr Lett, 5(6), pp.379-383. [pdf](https://www.researchgate.net/profile/Scott-Hotaling/publication/342155333_Simple_rules_for_concise_scientific_writing/links/5ee78b3692851ce9e7e3dc61/Simple-rules-for-concise-scientific-writing.pdf)  
- McPhee, J., 2017. Draft no. 4: On the writing process. Farrar, Straus and Giroux. [link](https://www.newyorker.com/magazine/2013/04/29/draft-no-4)  
- Schimel, J., 2012. Writing science: how to write papers that get cited and proposals that get funded. OUP USA. [pdf](https://wp.optics.arizona.edu/kupinski/wp-content/uploads/sites/91/2023/01/Writing_Science_Joshua_Schimel.pdf)


In addition to these more formal resources, here are some random thoughts and lessons learned about the writing process. These have been compiled the hard way and the easy way (i.e., from personal failure or from friends).

- Decide who you are writing to first. A mentor once told me that academic papers are like letters to our colleagues. I found this really empowering, and it made it far less scary.  
- "If I had time, I would have written a shorter letter." ([lots of people, apparently](https://quoteinvestigator.com/2012/04/28/shorter-letter/)) Brevity always takes more time than you think. Distilling a message may, however, be the most important part of writing.  
- If your writing project has multiple people involved, engage them in the process. However, it may be important to specify which type of feedback you are ready for: framing and big ideas, flow and paragraph level, or line level. 

# **Authorship Discussions**

Some of the most unpleasant moments in research and science can emerge during discussions of authorship, and this isn't irrational. In parts of the science community, publication is the currency of the field, and authorship is a major component of resume building (and job applications). More importantly though, people are invested in the work and feel strongly about their efforts being acknowledged. Unsurprisingly, there are loads of resources for navigating these issues, some of which are very formal and others less so.  

- Cooke, S.J., Nguyen, V.M., Young, N., Reid, A.J., Roche, D.G., Bennett, N.J., Rytwinski, T. and Bennett, J.R., 2021. Contemporary authorship guidelines fail to recognize diverse contributions in conservation science research. [pdf](https://www.fecpl.ca/wp-content/uploads/2021/03/2688-8319.12060.pdf)  
- Contributor Role Taxonomy (CRediT). https://credit.niso.org/  
- Dickson, J.G., Conner, R.N. and Adair, K.T., 1978. Guidelines for authorship of scientific articles. Wildlife Society Bulletin (1973-2006), 6(4), pp.260-261.


In my view, the following issues can help avoid or mitigate tensions about authorship.  

- Talk about it early to set expectations about workload and avoid hurt feelings on the back side. How early? I prefer to talk about it when a manuscript is conceived or outlined.  
- Revisit the conversation throughout the life of the project. People's careers change, the roles in project change, and projects simply evolve.  
- These issues are better discussed than emailed. Do it in person if possible. Start the conversation from a place of respect and understanding. Work from the assumption that someone is bringing up the topic because it matters to them and their feelings about attribution.  
- Co-author is a verb, not a noun. People need to be able to articulate how they contributed, which can be a breadth of activities.   
- It may be easiest to work through the discussion sequentially. Who are the main movers-and-shakers on the paper? They are usually the first and last author. From there, who should be on the authorship team at all? Sort through this yes or no level of contribution first. Finally, what was everyone's level of effort? Deal with order of middle authors.  
- On the whole, it is rarely (if ever) worth losing a colleague or damaging a relationship over authorship. 


# **Peer Reviewing**

Here are a series of quick checks I use after I have written something. I also apply these to peer review.  

- Remove the, this, that, there, etc.  
- Change “to be” verbs to action verbs because it makes the text more interesting.  
- Look for long sentences with too many prepositional phrases.  
- Remove punctuation from the title, if possible.

To write a more respectful review, I try to do the following.  

- Address comments at "the manuscript", not "the authors". You are not commenting on someone, but instead the work in front of you. Directing comments at them can be unintentionally hurtful.  
- For large-scale technical issues, I try to use a four part comment structure: (1) identify the problem, (2) describe the technical basis for the comment, (3) rate the significance or impact of the problem, and (4) recommend a mechanism for resolution. This (laborious) commenting process tends to lead to more constructive reviews in my experience.  
- The most common issue I encounter is over-reaching conclusions. Did the discussion flow from the methods or the results? Is the manuscript switching into editoriallizing about a topic?  
- Journals have useful guidance on this topic, like [this one](https://authorservices.wiley.com/Reviewers/journal-reviewers/how-to-perform-a-peer-review/step-by-step-guide-to-reviewing-a-manuscript.html). Use the tools. 


